# Generated by Django 5.1 on 2024-08-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
